####################################################
# Deployment vars
####################################################
# If you want the default values supplied by concourse-up,
# just put in an empty string
####################################################
domain: "ci.aegershman.com"
tls_cert: ""
tls_key: ""
workers: "1"
worker_size: "medium"
web_size: "small"
db_size: "small"
aws_region: "us-east-1"
project_name: "aegershman"

####################################################
# Misc. Config.
####################################################
# Pin concourse-up to specific versions to
# avoid params changing without our knowledge
concourse_up_tag_filter: "0.9.*"
pipeline_tasks_uri: https://github.com/aegershman/concourse-up-up.git
