####################################################
# Deployment vars
####################################################
# If you want the default values supplied by concourse-up,
# just put in an empty string
####################################################
domain: "ci.gershman.io"
tls_cert: ""
tls_key: ""
workers: "1"
worker_size: "medium"
web_size: "small"
db_size: "small"
aws_region: "us-west-2"
project_name: "gershman"

# AWS creds can be loaded from credhub, or just override them
# when you're setting the pipeline locally
aws_access_key_id: ((aws_access_key_id))
aws_secret_access_key: ((aws_secret_access_key))

####################################################
# Misc. Config.
####################################################
# Pin concourse-up to specific versions to
# avoid params changing without our knowledge
concourse_up_tag_filter: "0.13.*"
pipeline_tasks_uri: https://github.com/aegershman/concourse-up-up.git
pipeline_tasks_branch: polish