####################################################
# Deployment vars
####################################################
domain: ci.gershman.io
workers: 1
worker_size: xlarge
web_size: medium
db_size: small
aws_region: us-west-2
project_name: gershman

# AWS creds can be loaded from credhub, or just override them
# when you're setting the pipeline locally
aws_access_key_id: ((aws_access_key_id))
aws_secret_access_key: ((aws_secret_access_key))

####################################################
# Misc. Config.
####################################################
concourse_up_tag_filter: "0.13.*"
concourse_up_access_token: ((concourse_up_access_token))
pipeline_tasks_uri: https://github.com/aegershman/concourse-up-up.git
pipeline_tasks_branch: master
concourse_up_owner: EngineerBetter
concourse_up_repository: concourse-up